name: cookie-cutter
channels:
- conda-forge
- defaults
dependencies:
- numpy
- pandas
- xarray
- arm_pyart
- xlrd
- matplotlib
- jupyter
- cython
- wget
- lxml
- pyproj
- pip:
  - git+git://github.com/CSU-Radarmet/CSU_RadarTools.git